2025-04-09 00:04:40,881 ERROR: Exception on /shipments/ [GET] [in C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\shipments\routes.py", line 29, in list_shipments
    return render_template('shipments/list.html', title='Liste des Envois',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\temp\shipping_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\temp\shipping_app\app\templates\shipments\list.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\templates\base.html", line 198, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\templates\shipments\list.html", line 66, in block 'content'
    href="{{ url_for('shipments.view_shipment', id=shipment.id) }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'shipments.view_shipment' with values ['id']. Did you mean 'shipments.edit_shipment' instead?
2025-04-09 00:05:00,016 ERROR: Exception on /shipments/ [GET] [in C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\shipments\routes.py", line 29, in list_shipments
    return render_template('shipments/list.html', title='Liste des Envois',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\temp\shipping_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\temp\shipping_app\app\templates\shipments\list.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\templates\base.html", line 198, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\templates\shipments\list.html", line 66, in block 'content'
    href="{{ url_for('shipments.view_shipment', id=shipment.id) }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'shipments.view_shipment' with values ['id']. Did you mean 'shipments.edit_shipment' instead?
2025-04-09 00:09:12,921 ERROR: Exception on /shipments/ [GET] [in C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\shipments\routes.py", line 29, in list_shipments
    return render_template('shipments/list.html', title='Liste des Envois',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\temp\shipping_app\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\temp\shipping_app\app\templates\shipments\list.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\templates\base.html", line 198, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\app\templates\shipments\list.html", line 66, in block 'content'
    href="{{ url_for('shipments.view_shipment', id=shipment.id) }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\shipping_app\venv\Lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'shipments.view_shipment' with values ['id']. Did you mean 'shipments.edit_shipment' instead?
2025-04-09 00:09:22,516 INFO: Shipping App startup [in C:\temp\shipping_app\app\__init__.py:56]
